import { expect, test } from "@playwright/test";

const today = new Date();
const todayStart = `${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, "0")}${String(today.getDate()).padStart(2, "0")}T140000`;
const preferences = { onboardingComplete: true, name: "小程", role: "guide", quietStart: "23:00", quietEnd: "07:30", calendarEvents: [{ id: "event-1", summary: "Python 练习", start: todayStart, status: "confirmed" }] };
const agent = { schema_version: 1, long_term_goals: [{ text: "成为能独立完成产品的人" }], skills: { python: { label: "Python 基础", confidence: .9, evidence: ["完成函数练习"] }, database: { label: "数据库进阶", confidence: .45, evidence: ["开始整理查询笔记"] } }, next_recommended_action: { id: "suggestion-1", title: "完成一轮 Python 练习", why_now: "这是你刚才主动提起的方向。", duration_minutes: 20, status: "pending" } };
async function open(page, preview) { await page.addInitScript(({ preferences, agent }) => { localStorage.setItem("xuecheng:iphone:v2", JSON.stringify(preferences)); localStorage.setItem("xuecheng:agent:v1", JSON.stringify(agent)); }, { preferences, agent }); await page.goto(`/react.html?preview=${preview}`); }
test("390pt schedule separates confirmed entries and pending suggestions", async ({ page }) => { await open(page, "schedule"); await expect(page.getByRole("main", { name: "日程" })).toBeVisible(); await expect(page.getByText("建议 · 尚未写入日程", { exact: true })).toBeVisible(); await expect(page.getByText("Python 练习", { exact: true })).toBeVisible(); await page.screenshot({ path: "test-results/phase-5/schedule.png" }); });
test("390pt path uses only persisted goal and evidence", async ({ page }) => { await open(page, "path"); await expect(page.getByText("成为能独立完成产品的人", { exact: true })).toBeVisible(); await page.screenshot({ path: "test-results/phase-5/path.png" }); });
test("390pt profile presents settings through reusable rows", async ({ page }) => { await open(page, "profile"); await expect(page.getByRole("main", { name: "我的" })).toBeVisible(); await expect(page.getByText("跨设备同步", { exact: true })).toBeVisible(); await page.screenshot({ path: "test-results/phase-5/profile.png" }); });
